// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMm0c__foH2YkrA5V3b0DMLE7U5rEk5Jw',
    appId: '1:14908658070:web:bde2036c5a315f42660db7',
    messagingSenderId: '14908658070',
    projectId: 'financas-fb5dd',
    authDomain: 'financas-fb5dd.firebaseapp.com',
    storageBucket: 'financas-fb5dd.firebasestorage.app',
    measurementId: 'G-NRXKH3E0FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO5fxOQ_AE_14lzUZ1b91TEhvG2KB194k',
    appId: '1:14908658070:android:0fc3a5227935beda660db7',
    messagingSenderId: '14908658070',
    projectId: 'financas-fb5dd',
    storageBucket: 'financas-fb5dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOCk4klzoKXxSq_T_kj2rTWmZWaXY7cEY',
    appId: '1:14908658070:ios:19cae68c516fbb3d660db7',
    messagingSenderId: '14908658070',
    projectId: 'financas-fb5dd',
    storageBucket: 'financas-fb5dd.firebasestorage.app',
    androidClientId: '14908658070-fbslus09jto16202gs4etfvcevs98h5t.apps.googleusercontent.com',
    iosClientId: '14908658070-1o6b6i62s80ba3gn19paicjqlkpq8tlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.financas',
  );
}
